language: node_js
node_js:
  - "node"
env:
  - REACT_VERSION=15
  - REACT_VERSION=16
script:
  - npm install react@$REACT_VERSION
  - npm install react-dom@$REACT_VERSION
  - npm install react-test-renderer@$REACT_VERSION
  - make ci
after_script: node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
