language: node_js
node_js:
  - "node"
env:
  - REACT_VERSION=0.14
  - REACT_VERSION=15
script: make ci
before_script: npm i react@$REACT_VERSION react-addons-test-utils@$REACT_VERSION
after_script: node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
