language: node_js
node_js:
  - "node"
env:
  - REACT_VERSION=0.14
  - REACT_VERSION=15
script:
  - npm install xpath-evaluator
  - npm install react@$REACT_VERSION
  - make ci
after_script: node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
