language: node_js
node_js:
  - "node"
env:
  - REACT_VERSION=15
  - REACT_VERSION=16
install: make clean-install REACT_VERSION=$REACT_VERSION
script: make ci
after_script: node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
